### ISSUE TITLE
1.3.5 or 1.4.1 build

### ISSUE THREAD

**Issue by ScApi** [xdarklight/drv_mei_cpe#1]
Did You tried 1.3.5 or above to build or work with openwrt ? I've managed to compile them but I'm unable to make them working with openwrt (module not loading), not tested dsl_control and dsl_api as they don't work without mei loaded.

**Comment by xdarklight** [comment]
The update requires a bit of manual work unfortunately:
You first need to get a tarball of all updated packages (lib_ifxos, dsl_cpe_control_vrx, drv_mei_cpe, drv_dsl_cpe_api_vrx).
Then you need to apply this patch to your OpenWrt tree: https://gist.github.com/xdarklight/58fe9807594d5366e068/download

This made it compile and load on OpenWrt for me, see https://lists.openwrt.org/pipermail/openwrt-devel/2015-April/032399.html
Unfortunately I did not manage to get it connected (it stuck at 0x300 - HANDSHAKE) - but I had the same problems with the old 4.11.4 driver.

PS: I'm planning to simplify this patching process and do more experiments next week (as I finally have time then).

**Comment by ScApi** [comment]
Packages from BTHH or other source ? I've used Draytek ones.
I've missed whole thread on openwrt-devel, will check it now.

**Comment by ScApi** [comment]
It's working : http://pastebin.com/ne1aELff

Need to change cople of things in Your patch to match my packages.
DSL sync comes up on new firmwares (ADSL only, cannot test VDSL).
Many warnings, PPPOE didn't came up automaticly (needed to ifup wan).
Will test stability and dsl_controll script as it lacks of options.

Need to figure out how to disable ReTx, cos on ADSL it causes lot of warnings.
DSL[00]: ERROR - ReTx PM counters read failed!

**Comment by xdarklight** [comment]
Very nice, thanks for the update!

What firmware version are you using?
Try one of the firmwares that supports vectoring, see https://xdarklight.github.io/lantiq-xdsl-firmware-info/

**Comment by ScApi** [comment]
VDSL line is under testing, my only supports ADSL so I send firmware to friend.

Firmware:
xcpe_567517_562301.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 6.7.5 | ADSL Annex A for VRX200, version: 6.2.3

On ADSL Modem hangs after about 10 minutes flooded with:

 539.500000] MEI_DRV[00 - 01]: Send Msg[0x2B0A] read ACK failed (cnt: 5146, t: 239492 - 239500 = 8)
[  539.500000] 
[  539.508000] DSL[00]: Error -1008 during FIO_MEI_MBOX_MSG_SEND (MsgID=0x2B0A), FctCode 0x3100!
[  539.520000] DSL[00]: negative response for MsgID=0x2B0A (Class=0x00003100) - on try 0!
[  540.228000] DSL[00]: Error for send CMD MsgID=0x2B0A - KEEP line!
[  540.232000] DSL[00]: ERROR - ReTx PM counters read failed!
[  540.236000] DSL[00]: PM NE processing out of Poll Cycle!
[  540.248000] MEI_DRV[00 - 01]: ReadAck[0x2B0A] - FctOP ERROR 0x31!

**Comment by xdarklight** [comment]
I have no idea about those errors, sorry.
Maybe someone on the openwrt-devel mailing list can help out here.

**Comment by xdarklight** [comment]
You have figured it our yourself in the meantime :)
The following configuration options were missing in OpenWrt's Makefile:
`--enable-error_print \
    --disable-warning_print \
    --enable-debug-prints=no \`
